### ISSUE TITLE
UPD client instructions, 

### ISSUE THREAD

**Issue by ErkkiMehtala** [ARMmbed/mbed-example-network#33]
Should there be more spesific instructions
-How to check COM port (I used mbedls), ot to look from Device Manager
-how to get/use pyOCD in windows. I found it from C:\Python27\Lib\site-packages\pyOCD\gdbserver,
updated it (pip install -U pyOCD).

It is not in path so need to start it from there directly. Something missing:
python C:\Python27\Lib\site-packages\pyOCD\gdbserver\gdbserver.py
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 18, in
 <module>
    from ..target.target import Target
ValueError: Attempted relative import in non-package

gdbserver.py line 18:
  from ..target.target import Target
That module seems to be found in right place but not visible

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1070

**Comment by ErkkiMehtala** [comment]
Example itself works fine. But when trying debugger it gets mad (prints forever in command window, prints below. Maybe it is because of incomplete pyOCD installation. But is it that yotta should handle this situation better (exit with error code and not leave in endless loop)? And if this debugger is working just in linux, maybe it should be mentioned.

---------
-board not connected yet (this is maybe expected behauviour):

C:\Users\erkmeh01\OOB\mbed-example-network>yotta debug mbed-example-network-test
-helloworld-udpclient
info: found mbed-example-network-test-helloworld-udpclient at test\mbed-example-
network-test-helloworld-udpclient
info: preparing PyOCD gdbserver...
info: finding connected board...
No connected boards
error: failed to find a connected board
error: failed to launch debugger: gdb server failed to start
project files have been generated in: test

---
-board connected (with this example SW which was flashed earlier), eternal loop:

yotta debug mbed-example-network-test-helloworld-udpclient
... lots of prints, cannot catch from beginning  ...

    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions
error: Unexpected exception: [Errno 10013] An attempt was made to access a socke
t in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdbserver.py", line 310, i
n run
    connected = self.abstract_socket.connect()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 36, i
n connect
    self.init()
  File "C:\Python27\lib\site-packages\pyOCD\gdbserver\gdb_socket.py", line 31, i
n init
    self.s.bind(('', self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden b
y its access permissions

**Comment by bremoran** [comment]
It appears that you are experiencing some problems with pyOCD.  pyOCD should be installed automatically via yotta, since yotta depends on valinor, which depends on pyOCD.  These problems are not related to the UDP client instructions.  

Note that the UDP client does list yotta as a prerequisite and it provides a link to the yotta repo.  The yotta repo clearly provides instructions on how to install yotta.

I will add a note about discovering serial ports.
